Repository opentelekomcloud-infra/simple-exquisite-webserver, pull requests merged in 2019-10, with the labels that each got.

#24 fix stop
  main/main.go
Labels: bug

#26 Fix/del pid
  main/main.go
Labels: bug

#31 Fix not creating database
  .travis.yml
  main/app.go
  main/app_test.go
  main/main.go
  main/model.go
Labels: bug, enhancement

#33 Update license
  LICENSE
Labels: documentation

#32 Feature/data generation
  README.md
  main/app.go
  main/app_test.go
  main/configuration.go
  main/configuration_test.go
  main/entities.go
  main/fake_db.go
  main/main.go
  main/model.go
Labels: enhancement

#36 Fix not updated version
  main/main.go
Labels: bug, documentation

#38 Absolutely 100% last fix of `/entities?filter=...`
  main/main.go
  main/model.go
Labels: bug

#39 Fix not working --version flag
  main/main.go
Labels: bug
